---

- name: Add Mosquitto repository
  become: yes
  apt_repository:
    repo: ppa:mosquitto-dev/mosquitto-ppa
    state: present
    update_cache: yes
    validate_certs: no

- name: Ensure Mosquitto service is installed
  become: yes
  apt:
    name: "mosquitto={{ mosquitto.version }}"
    state: present

- name: Ensure Mosquitto clients
  become: yes
  apt:
    name: "mosquitto-clients={{ mosquitto.version }}"
    state: present
  when: mosquitto.install_clients

- name: Install Pip for boto
  become: yes
  apt:
    name: python-pip
  when: mosquitto.aws.enabled

- name: Install boto
  become: yes
  pip:
    name: boto
  when: mosquitto.aws.enabled

- name: Add ulimits to Upstart config
  become: yes
  lineinfile:
    line: "limit nofile {{ mosquitto.limits.nofile_soft }} {{ mosquitto.limits.nofile_hard }}"
    dest: /etc/init/mosquitto.conf
    regexp: "^limit nofile"
  when: ansible_service_mgr == "upstart"
  notify:
    - restart mosquitto

- name: Add ulimits to Sysvinit config
  become: yes
  lineinfile:
    insertafter: "^umask"
    line: "ulimit -Hn {{ mosquitto.limits.nofile_hard }} && ulimit -Sn {{ mosquitto.limits.nofile_soft }}"
    dest: /etc/init.d/mosquitto
    regexp: '^ulimit'
  when: ansible_service_mgr == "sysvinit"
  notify:
    - restart mosquitto
